// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    return ($('table .btn-primary')).click(function() {
      console.log('tu mama');
      return console.log('click');
    });
  });

}).call(this);
