// Generated by CoffeeScript 1.4.0
(function() {

  window.ButtonLoader = (function() {

    function ButtonLoader(buttonId) {
      this.buttonId = buttonId;
    }

    ButtonLoader.prototype.preload = function() {
      var c, classes, element, _i, _len;
      element = $("a[name=paymentRegistration" + this.buttonId + "] > i");
      classes = element.attr("class").split(" ");
      for (_i = 0, _len = classes.length; _i < _len; _i++) {
        c = classes[_i];
        element.removeClass(c);
      }
      return element.addClass('icon-refresh icon-spin');
    };

    return ButtonLoader;

  })();

}).call(this);
